### ISSUE TITLE
Hello and good luck with your plug-in! Sorry if this is a wrong place, but I can't find this plugin in homebridge library. Could you please give some instructions how to install? Thank you

### ISSUE THREAD

**Issue by tso33** [kovapatrik/homebridge-midea-platform#1]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kovapatrik** [comment]
I didn't want to publish it yet, because I wanted to test it a day or two and also the config scheme needs to be finalized. I will check if the plugin still works tomorrow and if it does I will publish it to npm.

**Comment by kovapatrik** [comment]
I've just published the package [homebridge-midea-platform](https://www.npmjs.com/package/homebridge-midea-platform). Let me know when you have tried it out and if everything worked fine or not.
