### ISSUE TITLE
Devices not appearing in HomeKit

### ISSUE THREAD

**Issue by jimmycap81** [kovapatrik/homebridge-midea-platform#106]
**Describe Your Problem:**

Hello, I’ve run the discovery portion of the script, and my devices have all been identified.  I then add them to the config yet they do not seem to “take.”  

My newly created Midea bridge appears when I go to add it in HomeKit, but none of the devices are added.  

Can you advise on what I’m doing wrong?

**Logs:**

9/1/2024, 11:45:09 AMMidea Platform Bridgemidea-platformStart device discovery...
9/1/2024, 11:45:09 AMMidea Platform Bridgemidea-platformDiscovered device: {"ip":"10.0.0.209","port":6444,"id":151732605585597,"model":"00000Q12","sn":"000000P0000000Q12459E54B2E460000","name":"net_ac_2E46","type":172,"version":3}
9/1/2024, 11:45:09 AMMidea Platform Bridgemidea-platformWARNING[net_ac_2E46 | 10.0.0.209}] New device discovered, you must add it to the config.json settings.
9/1/2024, 11:45:09 AMMidea Platform Bridgemidea-platformDiscovered device: {"ip":"10.0.0.106","port":6444,"id":151732605586729,"model":"00000Q12","sn":"000000P0000000Q12459E54790240000","name":"net_ac_9024","type":172,"version":3}
9/1/2024, 11:45:09 AMMidea Platform Bridgemidea-platformWARNING[net_ac_9024 | 10.0.0.106}] New device discovered, you must add it to the config.json settings.
9/1/2024, 11:45:09 AMMidea Platform Bridgemidea-platformDiscovered device: {"ip":"10.0.0.233","port":6444,"id":150633093958943,"model":"00000Q12","sn":"000000P0000000Q12459E549BC5A0000","name":"net_ac_BC5A","type":172,"version":3}
9/1/2024, 11:45:09 AMMidea Platform Bridgemidea-platformWARNING[net_ac_BC5A | 10.0.0.233}] New device discovered, you must add it to the config.json settings.
9/1/2024, 11:45:17 AMMidea Platform Bridgemidea-platformAll configured devices added to Bridge
9/1/2024, 11:49:25 AMMidea Platform Bridgemidea-platformStart device discovery...
9/1/2024, 11:49:25 AMMidea Platform Bridgemidea-platformDiscovered device: {"ip":"10.0.0.233","port":6444,"id":150633093958943,"model":"00000Q12","sn":"000000P0000000Q12459E549BC5A0000","name":"net_ac_BC5A","type":172,"version":3}
9/1/2024, 11:49:25 AMMidea Platform Bridgemidea-platformWARNING[net_ac_BC5A | 10.0.0.233}] New device discovered, you must add it to the config.json settings.
9/1/2024, 11:49:25 AMMidea Platform Bridgemidea-platformDiscovered device: {"ip":"10.0.0.209","port":6444,"id":151732605585597,"model":"00000Q12","sn":"000000P0000000Q12459E54B2E460000","name":"net_ac_2E46","type":172,"version":3}
9/1/2024, 11:49:25 AMMidea Platform Bridgemidea-platformWARNING[net_ac_2E46 | 10.0.0.209}] New device discovered, you must add it to the config.json settings.
9/1/2024, 11:49:25 AMMidea Platform Bridgemidea-platformDiscovered device: {"ip":"10.0.0.106","port":6444,"id":151732605586729,"model":"00000Q12","sn":"000000P0000000Q12459E54790240000","name":"net_ac_9024","type":172,"version":3}
9/1/2024, 11:49:25 AMMidea Platform Bridgemidea-platformWARNING[net_ac_9024 | 10.0.0.106}] New device discovered, you must add it to the config.json settings.
9/1/2024, 11:49:33 AMMidea Platform Bridgemidea-platformAll configured devices added to Bridge

**Plugin Config:**

See attached. 

**Screenshots:**

**Environment:**
Hoobs
![IMG_3434](https://github.com/user-attachments/assets/df3905f0-59af-4de9-aafb-766b904c340e)
![IMG_3435](https://github.com/user-attachments/assets/12c99d4b-4aed-42c0-9ae4-f9bbce2ea441)
![IMG_3434](https://github.com/user-attachments/assets/8fd08d9c-4248-40eb-8982-a064967dcc20)
![IMG_3436](https://github.com/user-attachments/assets/7839b963-e6a8-44fb-9c40-dc0d94faba5f)

- **Plugin Version**: 1.1.1
- **Homebridge Version**: 1.7.0
- **Node.js Version**: 16.20.2
- **NPM Version**: 
- **Operating System**:

**Comment by kovapatrik** [comment]
I think you used this plugin when it was in early development. The name of the platform now is `midea-platform` and the `ACoptions` changed to `AC_options`. I would suggest you to delete the configuration of this plugin, and reinstall the plugin just to be 100% sure.

**Comment by kovapatrik** [comment]
Also, when you add devices using the discovery method, don't forget to save the form! It's not saved automatically.

**Comment by jimmycap81** [comment]
Thank you so much.  1.1.1 is the latest version I’m seeing in the Hoobs library, and it’s dated  7/29/24.  See attached.  

The only other Midea plugins I see in the library are named something other than Madea Platform.  Also see attached. 

I’m sorry to have to ask this (am relatively new to this work), but do you have any further advice?
![IMG_3440](https://github.com/user-attachments/assets/b1583c8a-33c3-456f-bfac-1a7ccf3aeac0)
![IMG_3439](https://github.com/user-attachments/assets/82e431e6-bfa7-45f2-b997-fe989191f815)
![IMG_3438](https://github.com/user-attachments/assets/69a37fe7-cd45-4e3f-b272-8f992bf2093b)
![IMG_3437](https://github.com/user-attachments/assets/d9e36b8e-ecbe-4c38-911c-f89f84ec1662)

**Comment by kovapatrik** [comment]
I can only advise as I said before: remove any settings from the config JSON which is related to this plugin, reinstall the plugin, and add your devices again using the discovery flow.

**Comment by kovapatrik** [comment]
Feel free to message me if you got stuck, but it should be kinda straight forward.

**Comment by kovapatrik** [comment]
Have you had any success?

**Comment by jimmycap81** [comment]
No luck yet.  I’ve tried uninstalling and reinstalling.  Oddly, the version
I get through Hoobs claims to be 1.1.1, but when I go to configure the
devices in the graphical UI, it still generates the settings for each
device as “ACOption” not “AC_Option,” as you mentioned it should.

I should have perhaps mentioned that the devices in question are
Carrier-branded heat pumps.

Any thoughts most welcomed.

**Comment by kovapatrik** [comment]
I did a quick research about HOOBS. I've found this reddit post: https://www.reddit.com/r/homebridge/comments/z8t3n2/hoobs where the first comment is that a lot of plugin doesn't work with HOOBS. Also, I checked on the HOOBS repository and it got updates 3 years ago. I would say this is an issue with HOOBS and not with my plugin.

**Comment by kovapatrik** [comment]
A lot of people suggesting to just use stock Homebridge without HOOBS: https://www.reddit.com/r/homebridge/comments/192gvs8/questions_homebridge_vs_hoobs/

I never used HOOBS before, so I don't really know what it adds to Homebridge or what is it for overall.

**Comment by kovapatrik** [comment]
Closed because it's most likely a HOOBS issue, and HOOBS looks outdated.
