### ISSUE TITLE
Devices Not Being Discovered

### ISSUE THREAD

**Issue by bxn4488** [kovapatrik/homebridge-midea-platform#109]
**Describe Your Problem:**

I had to update the wifi on my Midea Portable AC Unit that was working fine with the plugin, and now I cannot discover it in the settings menu at all. It is now on a separate VLan from the Homebridge Host so I'm not sure if that is what may be causing an issue or not, but I wanted to reach out and see. 

**Environment:**

- **Plugin Version**:
- **Homebridge Version**: 
- **Node.js Version**: 
- **NPM Version**: 
- **Operating System**: MacOS

**Comment by dkerr64** [comment]
Yes, separate VLAN will be an issue. You can either add another network interface to the Homebridge on the same VLAN or you can set the actual IP address of the AC into the plugin config. 

The AC’s IP address must be reachable… make sure you can ping it from the Homebridge server.

**Comment by bxn4488** [comment]
Thank you for the information. How do I go about entering the IP Address into the plugin config without having the device id number? I apologize if I am missing something in the process. 

-Bruce

**Comment by kovapatrik** [comment]
You can also specify the IP address in the discovery flow, it's the last option in the form: 
![image](https://github.com/user-attachments/assets/2f8e0bc8-f18c-4429-b52d-92b6bbc9290f)

**Comment by kovapatrik** [comment]
Any success?

**Comment by bxn4488** [comment]
Yes, Thank you for reaching back out. I was able to get it find the device using the IP address. Thank you for your assistance.
