### ISSUE TITLE
Error: Cloud undefined is not supported.

### ISSUE THREAD

**Issue by gklka** [kovapatrik/homebridge-midea-platform#11]
**Describe The Bug:**

After updating it today via the Homebridge interface, I've got the following error, which is happening in loop:

```
[9/23/2023, 4:39:44 PM] [homebridge-midea-platform] Loaded homebridge-midea-platform v0.2.0 child bridge successfully
[9/23/2023, 4:39:44 PM] Loaded 1 cached accessories from cachedAccessories.0EB0B6F887F0.
Error: Cloud undefined is not supported.
    at Function.createCloud (/usr/lib/node_modules/homebridge-midea-platform/src/core/MideaCloud.ts:249:15)
    at new MideaPlatform (/usr/lib/node_modules/homebridge-midea-platform/src/platform.ts:38:31)
    at ChildBridgeFork.startBridge (/usr/lib/node_modules/homebridge/src/childBridgeFork.ts:150:42)
```

**To Reproduce:**
Just started it

**Expected behavior:**
It worked before the update

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
        {
            "user": "*******",
            "password": "*******",
            "useChinaServer": false,
            "devices": [
                {
                    "ip": "192.168.0.182",
                    "name": "kondika",
                    "deviceType": "AC",
                    "ACoptions": {
                        "outDoorTemp": false,
                        "audioFeedback": false,
                        "minTemp": 16,
                        "maxTemp": 30,
                        "tempStep": 1,
                        "fahrenHeit": false,
                        "fanOnlyMode": false
                    }
                }
            ],
            "_bridge": {
                "username": "0E:B0:B6:F8:87:F0",
                "port": 47560
            },
            "platform": "midea"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.2.0
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 18.17.1
* **NPM Version**: 9.6.7
* **Operating System**: Ubuntu / Linux hitchcock 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kovapatrik** [comment]
With the updates I've added new fields to the config scheme. Just open the plugin's setting with the GUI and save it.

**Comment by dkerr64** [comment]
Plugin version updates should not break existing installs.  Also, devices array should be optional -- the plugin should be able to operate in a default mode without explicitly listing all devices in the config by discovering all devices from the LAN.

**Comment by kovapatrik** [comment]
Well I can't add the default values to someone's settings, so it will break if the config scheme is changed.

I've implemented the discovery mode, but it wasn't constitent, sometimes not all of my ACs responded to the discovery message.

**Comment by dkerr64** [comment]
Yes, I think you need both.  Discovery is the easiest for users, but you do need to be able to specifically list known devices.  I'd like to help improve this.
