### ISSUE TITLE
 robot vacuum cleaner

### ISSUE THREAD

**Issue by juliojmjc** [kovapatrik/homebridge-midea-platform#15]
**Is your feature request related to a problem? Please describe:**
 robot vacuum cleaner start cleaning

**Describe the solution you'd like:**
pick a button to start

**Comment by kovapatrik** [comment]
Robot vacuum cleaner is not suppoted yet.

**Comment by kovapatrik** [comment]
Unfortunately I can't find any documentations about controlling a Midea robot vaccuum cleaner through LAN. The protocol of the robot must be reversed-engineered somehow by somebody who has a unit.

**Comment by kovapatrik** [comment]
I would try to contact with some people in this project whether or not your robot is supported: https://github.com/Hypfer/Valetudo

The official support list doesn't contain any Midea unit, but maybe someone tried it in the past...

**Comment by kovapatrik** [comment]
Closed until more informations can be found for controlling robot vacuum cleaner.

**Comment by kovapatrik** [comment]
I've found a solution which might work, but I will need your assistance. Are you still interested in this feature?

**Comment by kovapatrik** [comment]
Closed until response or need for this feature.
