### ISSUE TITLE
Midea dongle OSK102 / OSK103 / OSK105

### ISSUE THREAD

**Issue by boboxx** [kovapatrik/homebridge-midea-platform#2]
Are Midea dongle OSK102 / OSK103 / OSK105 all supported?

**Comment by kovapatrik** [comment]
I only have an OSK105 dongle, but if I have to guess then I would say yes, it supports all of them. Hopefully I can publish the plugin to npm tomorrow and you can test it then. Any feedback is appreciated!

**Comment by tso33** [comment]
I use midea_ac_lan,georgezhao2010 and OSK102 works perfectly. So if you use this library, maybe it's ok.! 

I noticed that display off feature used to work on older versions of midea_ac_lan,georgezhao2010 and no on newer, but I think this is a next step fix and other fixes have priority

**Comment by kovapatrik** [comment]
I've managed to control the display of the AC, but it looks like when querying if the display is on or off, the AC always respondes with on.

**Comment by kovapatrik** [comment]
I will check on it! In the meanwhile I've published the package as "homebridge-midea-platform".

**Comment by gimprota76** [comment]
OSK105 work!

**Comment by kovapatrik** [comment]
So OSK103 and OSK105 are verified. 
I will close this for now. Can be reopened if some other dongle is not compatible.
