### ISSUE TITLE
2 new options

### ISSUE THREAD

**Issue by boboxx** [kovapatrik/homebridge-midea-platform#21]
Option to turn off the head unit LCD display
Option to turn on Frost Protection (FP mode), it allows heating to 10 deg C.

**Comment by kovapatrik** [comment]
The LCD switch is already added to the plugin. You can enable it in the config.

**Comment by boboxx** [comment]
Ok I will give it a try thanks

I see FP is discussed here in the midea_ac_lan group also:
https://github.com/georgezhao2010/midea_ac_lan/issues/141

**Comment by boboxx** [comment]
Ok I tried just about every combination of true/true, true/false, false etc.

Do have have the correct parameter?
   "switchDisplay": {
                            "flag": true,
                            "command": true
                        },

What values would I set to turn off the LED display after a change, or have it off completely?

**Comment by kovapatrik** [comment]
What do mean? The `flag` field decides if a switch will be created in the Home app or not. The `command` field is only need to be set to true if the switch does nothing when it's on false (which is the default).

**Comment by boboxx** [comment]
ok mabe I missunderstood, I'm looking for the option in the config to chnage the LED :)

**Comment by boboxx** [comment]
Well I'm a idiot! I had some how reenable the old plugin! I see see the 2 extra switches now and everything works!
