### ISSUE TITLE
Temperature Step & unsupported attribute log

### ISSUE THREAD

**Issue by tso33** [kovapatrik/homebridge-midea-platform#22]
Hello,

2 bugs:

1. I change temperature step to 0.5 from settings but after restart its 1 again. In the config file the is no option for temperature step.

![Screenshot 2023-10-17 at 19 09 09](https://github.com/kovapatrik/homebridge-midea-platform/assets/60290526/458c493e-a4cf-4ddf-97a1-b73fe11742de)

2. when I restart homebridge I get these at log

![Screenshot 2023-10-17 at 19 06 42](https://github.com/kovapatrik/homebridge-midea-platform/assets/60290526/a8fbac8f-47c3-4934-8847-91cf0938acb6)

Thank you!

**Comment by kovapatrik** [comment]
1. I've just made a fix for it.
2. The warning messages contains settings which are sent from the device, but there are no corresponding field available in Apple Home. If it' misleading or annoying there line can be hidden.
