### ISSUE TITLE
Change the prettier `printWidth` setting to something wider than 80 please.

### ISSUE THREAD

**Issue by dkerr64** [kovapatrik/homebridge-midea-platform#24]
Not sure this warrants opening an issue, but can we change the prettier `printWidth` setting to something wider than 80 please.  I am not finding it at all pretty when I am arbitrarily forced to line split perfectly reasonably wide lines.  It is really frustrating when two lines are similar in function (e.g. assigning a to b) but because variable names are of different length one is forced to be split into two and the other is not.

eslint allows for a line max-len of 140... can we set prettier to the same please.

I've made this change locally in my .prettierrc file and I'm a whole lot happier with the results. :-)

**Comment by kovapatrik** [comment]
Yeah, sure thing! You could have just create a PR :D As I said I don't insist any settings, I just want to see consistent line breaks, semicolons, etc...
