### ISSUE TITLE
Error API

### ISSUE THREAD

**Issue by tso33** [kovapatrik/homebridge-midea-platform#3]
Hello

Just installs this plugin and I got this:

9/14/2023, 2:18:48 PM] [midea] Error while sending request to https://mp-prod.appsmb.com/mas/v5/app/proxy?alias=/v1/user/login/id/get: Error: Error response from Midea cloud: value is illegal.
[9/14/2023, 2:18:48 PM] [midea] Error logging in to Midea Cloud: Error: Error response from Midea cloud: value is illegal.

Thanks you!

**Comment by kovapatrik** [comment]
Sorry, I forgot to mention that you must use a Midea account which is working in Midea SmartHome or Midea MSmartHome applications and you have to pair the devices with that account.

**Comment by tso33** [comment]
I use Midea SmartHome

![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/60290526/c1e58d19-95aa-41c1-8fe5-520e89419693)

![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/60290526/9151d53a-8e43-4681-96eb-9f89f961b4c7)

**Comment by kovapatrik** [comment]
And did you enter your credentials in the plugin settings?

**Comment by tso33** [comment]
Plug-in doesn't ask for credentials... I though that this plugin works with lan as georgezhao plugin sorry my bad:

![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/60290526/64151288-75ba-4e1b-81d3-5df27701daf5)

**Comment by kovapatrik** [comment]
Hm, you are right, the login settings are missing. I will fix this in a moment.

It works on LAN, but a token and key can only be obtained through the cloud. After the token and key is saved, no the cloud API won't be used.

**Comment by kovapatrik** [comment]
I've published an update. Could you please update it and check if the fields are there?

**Comment by tso33** [comment]
Field are there, office AC added successfully, I did 3-4 tests with fan speed, temperatures etc and everything works perfectly!! Finally someone did it!

**Comment by kovapatrik** [comment]
I'm glad it worked! Sometimes the connection closes for some reason and the control won't work (I've experienced this a few times, but it's totally random). But after that the plugin will automatically reconnect in some time, so it should work again.

**Comment by kovapatrik** [comment]
Btw, which dongle you have?

**Comment by tso33** [comment]
OSK102 I think..
