### ISSUE TITLE
Cleanup README

### ISSUE THREAD

**Issue by kovapatrik** [kovapatrik/homebridge-midea-platform#31]
@dkerr64 I appreciate your work on documenting all the things, but I think most part should be moved to the Wiki, and only the most important things should be in the README.md.

Thoughts?

**Comment by dkerr64** [comment]
I don't have strong opinion here, so long as instructions are easy to find.  Basic install/setup should be in the README as that is what most people will need.  But details on config.json and specific devices could be moved to the wiki... with the README directing folks to that.

**Comment by kovapatrik** [comment]
Yeah, I thought the same. I just see that if there are more device types, the readme won't scale nicely.

**Comment by dkerr64** [comment]
Next time we're touching package.json we need to handle this.

`The plugin "homebridge-midea-platform" requires Node.js version of ^18.17.0 which does not satisfy the current Node.js version of v20.9.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF`

I just upgraded the node version on my production server and get this message from several plugins!  Everything still works.

**Comment by kovapatrik** [comment]
Nice catch! Weird that the official Homebridge plugin has the Node version contraint fixed on v18.

**Comment by dkerr64** [comment]
> Nice catch! Weird that the official Homebridge plugin template has the Node version contraint fixed on v18.

I have opened a issue over on the template... https://github.com/homebridge/homebridge-plugin-template/issues/62

**Comment by kovapatrik** [comment]
Done with  #71
