### ISSUE TITLE
Error when accessory is restored from cache

### ISSUE THREAD

**Issue by kovapatrik** [kovapatrik/homebridge-midea-platform#4]
**Describe The Bug:**

It looks like the context of the accessory isn't totally saved:

**To Reproduce:**

1. Setup the plugin
2. Add device
3. Restart Homebridge

**Expected behavior:**

The platform should restore the whole accessory without a problem.
**Logs:**
```
TypeError: this.accessory.context.device.send_heartbeat is not a function
```

**Comment by tso33** [comment]
So far everything seems ok! I'll wait for display off function and I'll switch to this plugin!

Thank you very much!

**Comment by kovapatrik** [comment]
Cool, thanks for the info!

**Comment by kovapatrik** [comment]
@tso33 How does the display switch button looks like in other appliances? I've managed to put a huge switch under the AC settings in the Home app but is looks kinda bad.

**Comment by tso33** [comment]
Like a separate normal button

![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/60290526/36955b84-46df-447f-87e8-178fc6d25963)

**Comment by kovapatrik** [comment]
Ah okay. Is there a way in Apple Home to seperate accessories? For example my plugin add the outdoor temperature sensor for the air conditioner, but they appear in a single group, thus fan speed and the swing mode cannot be set from the main tile in the Home app. I had to click on the AC, then on the Accessories menu and there were the two serive: the AC one, and the tempreature sensor. So I there a way so ungroup these?

**Comment by tso33** [comment]
Hmm complicated... You can separate accessories in HomeKit but in your accessory with outdoor temperature I can't, there is no option... We can try it to see if we can use it in automations..

**Comment by kovapatrik** [comment]
I think you can use it, it just not intuitive that you have to go throught the mentioned process to set the fan speed for example.

**Comment by kovapatrik** [comment]
I've found a plugin which has a flag in the configuration of the device if the accessories for the device should be grouped (as in my plugin right now) or ungrouped (as you mentioned it). I think I will do the same, the question is: which setting should be default? Grouped or ungrouped?

**Comment by tso33** [comment]
Grouped!
