### ISSUE TITLE
Gain Homebridge Verification

### ISSUE THREAD

**Issue by simplytoast1** [kovapatrik/homebridge-midea-platform#46]
**Is your feature request related to a problem? Please describe:**

This is not related to a problem, rather an enhancement.

**Describe the solution you'd like:**

I would love if the plugin could become Homebridge verified. (https://github.com/homebridge/homebridge/wiki/Verified-Plugins).  It seems you already meet all the requirements.

**Describe alternatives you've considered:**

**Additional context:**

This helps with the discovery of quality Homebridge plugins.

**Comment by kovapatrik** [comment]
I've already planned this, just wanted to wait a bit for tests before an v1.0.0 release. After that I will start the process to verify the plugin.

**Comment by kovapatrik** [comment]
https://github.com/homebridge/verified/issues/703
