### ISSUE TITLE
Swing mode cause homebridge restart

### ISSUE THREAD

**Issue by tso33** [kovapatrik/homebridge-midea-platform#5]
I used the swing function from HomeKit and this cause an error and loop homebridge restart

![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/60290526/b3c3b6ef-4f18-4b56-bf61-2d541e0a72df)

And then after restart

![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/60290526/7e0a1a69-bc38-4b1f-8ab9-f8d3e6c05b6b)

Not important, I don't use swing but fyi

**Comment by kovapatrik** [comment]
I've just released a new version, but it changed some things in the config file itself, so the plugin will break if you at least don't save the config file from the settings menu (so the new fields will be set). The screen display switch should work now, but there is a toggle in the config, which activates the use of an alternate command to control the display.

**Comment by tso33** [comment]
Everything seems ok! One note: display off feature button if I sometimes has reverse status.
When display is on the switch status is off, but not often!

**Comment by kovapatrik** [comment]
Yeah, I've experienced the same. The command (which is sent to the AC) is a toggle command itself, so it doesn't take any inputs. So if the state in the Home app is out of sync, then it will do what you have described.

**Comment by tso33** [comment]
hmm ok! The outdoor sensors how often refresh the values? Only when AC is on?

**Comment by kovapatrik** [comment]
Yes, when the AC is off the unit always sends a falses value as the outdoor tempreature.

**Comment by tso33** [comment]
Ok! Thank you!
