### ISSUE TITLE
AC outdoor temp created despite config set to false

### ISSUE THREAD

**Issue by ftrela4991** [kovapatrik/homebridge-midea-platform#50]
**Describe The Bug:**

When setting outdoor temp checkbox to false, HomeKit still shows it as one of the temperature sensors

**To Reproduce:**

1. Add AC device to Midea Platform plugin
2. Expand "Air Conditioner Options" settings panel in plugin configuration
3. Un-check "Outdoor temperature" checkbox
4. Save changes and restart

**Expected behavior:**

After un-checking outdoor temperature in config, it should not show up in HomeKit

**Logs:**

```
[11/20/2023, 12:18:35 AM] [homebridge-midea-platform] [Midea Air] Value for OUTDOOR_TEMPERATURE changed from '9' to '9.1'
[11/20/2023, 12:18:35 AM] [homebridge-midea-platform] [Midea Air] Status change: {"OUTDOOR_TEMPERATURE":9.1}
[11/20/2023, 12:18:35 AM] [homebridge-midea-platform] [Midea Air] Set attribute OUTDOOR_TEMPERATURE to: 9.1
[11/20/2023, 12:18:35 AM] [homebridge-midea-platform] [Midea Air] Attempt to set unsupported attribute OUTDOOR_TEMPERATURE to 9.1
[11/20/2023, 12:18:35 AM] [homebridge-midea-platform] [Midea Air] Status unchanged
```

**Plugin Config:**

```json
        {
            "devices": [
                {
                    "type": "Air Conditioner",
                    "name": "Midea Air",
                    "id": "<ID>",
                    "advanced_options": {
                        "token": "<TOKEN>",
                        "key": "<KEY>"
                    },
                    "AC_options": {
                        "swingMode": "Both",
                        "outDoorTemp": false,
                        "ecoSwitch": false,
                        "switchDisplay": {
                            "flag": false
                        }
                    }
                }
            ],
            "platform": "midea-platform"
        }
```

**Environment:**

- **Plugin Version**: v0.4.10
- **Homebridge Version**: v1.7.0
- **Node.js Version**: v20.9.0
- **NPM Version**: v10.1.0
- **Operating System**: macOS Sonoma

**Comment by kovapatrik** [comment]
You sure it's added to the Home app too? The log will be there regardless of you set the Outdoor Tempreature checkbox or not. All attributes which are available in the Home app will logged out (so for example in this case the outdoor temperature).

**Comment by ftrela4991** [comment]
Yes, it’s still in HomeKit - I forgot to attach a screenshot, there it is:
![IMG_0081](https://github.com/kovapatrik/homebridge-midea-platform/assets/106706169/d7c0b8b3-f9f4-4726-a21c-94c7e8b384bd)

I’ll gladly submit any other necessary information. The work you’re doing is amazing, my AC with OSK103 dongle doesn’t work with any other homebridge plugin

**Comment by kovapatrik** [comment]
I've released a new version a few moments ago. Can you check if it fixes it?

@dkerr64 I accidently pushed into the main... I cleaned up some code in the DehumidiferAccessory as well (that part was needed for the `singleAccessory` field).

**Comment by dkerr64** [comment]
> @dkerr64 I've accidentally pushed into the main... I cleaned up some code in the DehumidiferAccessory as well (that part was needed for the `singleAccessory` field).

Ok, thanks.

**Comment by ftrela4991** [comment]
> I've released a new version a few moments ago. Can you check if it fixes it?
> 
> @dkerr64 I've accidentally pushed into the main... I cleaned up some code in the DehumidiferAccessory as well (that part was needed for the `singleAccessory` field).

Yes, I can confirm. Thank you for a prompt response and a fix!
