### ISSUE TITLE
Fan only mode for air conditioner

### ISSUE THREAD

**Issue by kovapatrik** [kovapatrik/homebridge-midea-platform#58]
Implement the fan only mode for air conditioner.

@bgeri85 I still owe you with this one:D

**Comment by kovapatrik** [comment]
Fan only mode got added with version v0.4.13. @bgeri85 Can you test it please?

**Comment by kkptrck** [comment]
Currently not working with EU-OSK105 wifi module. Any chance to make it work? Would be perfect. 🥺 Anyway your work is already greatly appreciated!

**Comment by kovapatrik** [comment]
Could you please be more specific what's not working? Is it the fan only mode? Or the whole plugin? In any case, can you attach your logs?

**Comment by kkptrck** [comment]
It is just the fan only mode. When I simply press on the fan tile in Home app, the AC wouldn’t turn on. 

![IMG_2850](https://github.com/kovapatrik/homebridge-midea-platform/assets/160386717/00c0c2fb-4100-42a9-a6d1-f838e76e5049)

Here’s the log for this event:
[2/22/2024, 1:32:01 PM] [midea-platform] [Fisher SE] Set device attribute MODE to: 5
[2/22/2024, 1:32:01 PM] [midea-platform] [Fisher SE] Status change: {"FAN_SPEED":102}

After that just setting to 60%
[2/22/2024, 1:36:15 PM] [midea-platform] [Fisher SE] Set device attribute FAN_SPEED to: 60

**Comment by kovapatrik** [comment]
Is it working if you turn on your AC before trying to use fan-only mode?

**Comment by kovapatrik** [comment]
In the next update this will be fixed. I will let you know when it's released.

**Comment by kkptrck** [comment]
Awesome, thanks for your efforts.

**Comment by kovapatrik** [comment]
I've released the version which includes this feature, can you test it out please?

**Comment by scaryfast8750** [comment]
Does not work for me.  If I put the unit in cool mode from the app, it shows in HomeKit OK.  But there is no option in HomeKit to chose fan only.

![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/88514039/04abe710-103f-42c5-a555-126462e8de13)

**Comment by kovapatrik** [comment]
Closed until further updates.
