### ISSUE TITLE
Add button for Breeze Away funcion.

### ISSUE THREAD

**Issue by leandromagro** [kovapatrik/homebridge-midea-platform#62]
Hi guys
In the Midea App (Smart home) there is a button for newer devices called Breeze Away. When clicked it sets the AC parameters for wind direction to the upmost position and the fan speed to 1%. And only works in Cool, Fan or Dry modes. I don’t know tho if there is any other parameter set behind the scenes.
Have a button like this, displayed togheter with the display and Fan mode, would be very useful.
Thanks!

**Comment by kovapatrik** [comment]
With version v0.4.13 I've added the option to add the breeze away switch to Apple Home. Can you  please test it?

**Comment by leandromagro** [comment]
Hi @kovapatrik 
Thanks for your prompt response.
I've tested and it is working. I've validated with the app.
BR.
