### ISSUE TITLE
Add Dry mode to AC

### ISSUE THREAD

**Issue by BrutallDLX** [kovapatrik/homebridge-midea-platform#63]
I would really like to have the option to integrate the Dry Mode, which is the only mode that is missing. Thanks!

**Comment by kovapatrik** [comment]
I think this feature is blocked by Apple Home limitations as dry mode is not available by default and custom options cannot be added as far as I know. I can create a switch for you which can turn on dry mode, but I think this way the usage wouldn't be that intuitive.

**Comment by kovapatrik** [comment]
I will add a switch in the next version of the plugin. I will let you know when it's released.

**Comment by kovapatrik** [comment]
I've released the version which includes this feature, can you test it out please?

**Comment by BrutallDLX** [comment]
Hi, yes! It worked! At least as a switch as you said because of HomeKit limitations. Thanks for the update!
