### ISSUE TITLE
Styling of switches

### ISSUE THREAD

**Issue by kovapatrik** [kovapatrik/homebridge-midea-platform#65]
I've found out today that it's possible to group switches like this: https://user-images.githubusercontent.com/32489848/73169444-bf194380-4104-11ea-99cc-54ddeea53117.PNG

Or buttons like this: 
![Jvz3xkT](https://github.com/kovapatrik/homebridge-midea-platform/assets/44952801/dc0d256b-875a-4a29-a717-446e1b2388ac)

I think this is much nicer than the current solution.

@dkerr64 what do you think?

**Comment by dkerr64** [comment]
If you group multiple accessories of the same type then this is how Apple Home displays the switches/lights by default... and the app also gives you the option to "Show as Separate Tiles".

To group multiple accessories of the same type you need to use ServiceLabels.  See an example implementation for a power strip [here](https://github.com/dkerr64/homebridge-yolink/blob/d44e5a3c1eb9c6bb5b70cd42355010fb129eb10b/src/outletDevice.ts#L40).

**Comment by kovapatrik** [comment]
Yeah, but currently they are all grouped. The problem is, that the accessories which are grouped must be the same type of accessory if I have to guess, because if not they will look like as now.

**Comment by kovapatrik** [comment]
I've tried out the ServiceLabel thing but without any success: I've added an index for each of the services starting from 1 (with the AC itself) to the bottom, ending with fan-only mode but it looked like it doesn't have any effect (they were in pseudo random order and the switches weren't grouped at all). Maybe the services must have the same type? 

If you have time, can you check this with the dehumidifer? You had success with the ServiceLabel previously on your repo, maybe I just screw up something.
