### ISSUE TITLE
Homekit no control

### ISSUE THREAD

**Issue by TPF1** [kovapatrik/homebridge-midea-platform#66]
Hi! I can switch ON/OFF all AC units from homeridge control but in homekit they just stay grayed out and no way to control them.

**Comment by kovapatrik** [comment]
If you can control them from the Homebridge UI then my plugin is working as expected. Maybe your pairing with the Homebridge Child Bridge is broken or something, but it's not related to the plugin.

**Comment by TPF1** [comment]
Ive restarted all bridge, hub and rooter. Now working! thanks
