### ISSUE TITLE
Plugin is exposing AC as a Heater-AC

### ISSUE THREAD

**Issue by rogersjc42** [kovapatrik/homebridge-midea-platform#68]
**Describe The Bug:**

AC Is exposed as a Heater-AC in the Home app. There are no logs for this error, as the information is presented inside the Home app.

**To Reproduce:**

1. Configure an AC
2. Inspect device in the Apple Home app
 

**Expected behavior:**
Device is properly presented to the Home app with the correct functionality

**Plugin Config:**
```
{
    "devices": [
        {
            "type": "Air Conditioner",
            "name": "Office AC",
            "id": 30786326306583,
            "advanced_options": {
                "token": "",
                "key": ""
            },
            "AC_options": {
                "swingMode": "Vertical",
                "audioFeedback": true,
                "fahrenheit": true
            }
        }
    ],
    "_bridge": {
        "username": "",
        "port": 
    },
    "platform": "midea-platform"
}
```

**Screenshots:**

![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/19679596/aab63ef6-a78b-4c38-b39b-f3e826b11740)

**Environment:**

- **Plugin Version**:  0.4.13
- **Homebridge Version**:  1.7.0
- **Node.js Version**:  18.19.0
- **NPM Version**:  10.2.3
- **Operating System**:  Docker

**Comment by kovapatrik** [comment]
So your problem is that your AC can't heat and the option is still there?

**Comment by rogersjc42** [comment]
Correct, the portable AC model that I have has no heater function yet the option still shows in the Home app. I assume this is from how it is exposed to the Home app from the Homebridge plugin

**Comment by kovapatrik** [comment]
Yes, the plugin currently assumes it can heat as well. I will add an option to hide heating in the next update.

**Comment by kovapatrik** [comment]
So if your AC is not heating capable, the only options you would need in the app is `Off` and `Cool`?

**Comment by kovapatrik** [comment]
And what do you think: should the plugin assume that the AC is heating capable by default? So in this case you would need to see through the config and turn it off. Or it can work in a reverse way, I don't know which one is more user friendly.

**Comment by rogersjc42** [comment]
I would be curious if the device reports back the capabilities? I don't know much about what the device is sending.

I think, in lieu of that,  I think defaulting as **AC only** is probably best. The Consumer Safety Product Commission (as well as most state and municipal fire codes afaik) in the United States have regulations against selling devices that allow the remote control (read: different location) of heaters due to concerns about fires. For all portable heaters (such as Dyson Cool+Hot fans), the heating controls are disabled both in the Dyson app as well as the Dyson Homebridge plugin.

In either case, I do think the option should be configurable if only to prevent you from being asked for the feature in the future, lol.

**Comment by kovapatrik** [comment]
Ah okay, I wasn't aware of the regulations in the USA, so I'll set it to `false` as a default. 

By the way, if I understand correctly, it's not possible then to have an AC in the USA which can also heat?

**Comment by rogersjc42** [comment]
It is possible to have a portable AC/Heater in the US, it is just not very common. It is about how the device is controlled. Basically, for a device that heats, the control mechanism must be affixed to the housing of the heater itself. It's a really weird regulation, imo, but such as it is.

**Comment by kovapatrik** [comment]
Thanks for the explanation!

So if an AC doesn't have heating capability, what would you expect the interface for the AC in the Home app to look like? Should it only have a `Heat` and an `Off` option?

**Comment by kovapatrik** [comment]
I've released the version which has the capability to config if your AC can do heating or not.
