### ISSUE TITLE
Lua and plugin files download for unsupported devices

### ISSUE THREAD

**Issue by kovapatrik** [kovapatrik/homebridge-midea-platform#69]
@dkerr64 There are 2 endpoints on Midea servers which provide information about the specified device, so in case someone wants support for a device which is not supported by the other plugin it would be possible (in theory) to use these files to reverse engineer the packets, etc... for the device and create the code for it. I've already implemented part of the code in `feat/e2-support` which will handle the downloading of the files.

The question is: how the flow should look like? My suggestion is to add a button in the config UI when there is an unsupported button. The button will download both of these files, and there should be a popup somewhere to create an issue and attach these files. I just don't know how user-friendly it is to download 2 random files from 2 random URLs without knowing what they really are. I mean they should mean no harm, but I would kind of understand if a user wouldn't want to download these without at least seeing the URL or something, but I might overthink this a bit.

What do you think?

**Comment by dkerr64** [comment]
Not sure I have a strong opinion.  But certainly anything that makes it easier for a user to capture required information and submit it in an issue to ease adding support for an unknown device sounds like a good thing.

**Comment by kovapatrik** [comment]
This feature will be available with the next release.
