### ISSUE TITLE
Missing support for Air Conditioner: Midea MFP-120i / Midea AMS150-PB

### ISSUE THREAD

**Issue by michasoellner** [kovapatrik/homebridge-midea-platform#74]
**Describe Your Problem:**

Hello. The Device is found in the discover Settings, but it's unsupported.

**Logs:**

[4/1/2024, 6:23:58 PM] [homebridge-midea-platform] Loaded homebridge-midea-platform v1.0.0 child bridge successfully
[4/1/2024, 6:23:58 PM] Loaded 0 cached accessories from cachedAccessories.0E9CCA24490B.
[4/1/2024, 6:23:58 PM] [homebridge-midea-platform] Start device discovery...
[4/1/2024, 6:23:58 PM] Homebridge v1.7.0 (HAP v0.11.2) (homebridge-midea-platform) is running on port 39442.
[4/1/2024, 6:23:58 PM] [homebridge-midea-platform] Discovered device: {"ip":"192.168.1.72","port":6444,"id":152832****0970,"model":"560000AG","sn":"0000FA************01734SPDC","name":"midea_fa_1734","type":250,"version":3}
[4/1/2024, 6:23:58 PM] [homebridge-midea-platform] Device type is unsupported by the plugin: 250
[4/1/2024, 6:24:06 PM] [homebridge-midea-platform] All configured devices added to Homebridge

**Plugin Config:**

{
    "devices": [
        {
            "type": "Air Conditioner",
            "name": "Midea",
            "id": 152832*********9070,
            "advanced_options": {
                "ip": "192.168.1.72",
                "verbose": true
            },
            "AC_options": {
                "swingMode": "Horizontal",
                "audioFeedback": true
            }
        }
    ],
    "_bridge": {
        "username": "0E:9C:*****0B",
        "port": 39442
    },
    "platform": "midea-platform"
}

**Screenshots:**

<img width="771" alt="Bildschirmfoto 2024-04-01 um 18 38 37" src="https://github.com/kovapatrik/homebridge-midea-platform/assets/73249924/1a80844a-4fde-4321-974e-920e26692bc0">

**Environment:**

- **Plugin Version**:
- **Homebridge Version**: v1.7.0
- **Node.js Version**: v20.12.0
- **NPM Version**: v10.5.0
- **Operating System**: UNRAID Homebridge Docker

**Comment by kovapatrik** [comment]
Well this is indeed a different device than what the plugin currently supports. You can see in the docs which devices are currently supported, with the type ID as well. Your device's ID is `FA` (it's in the `name` property of the device).

I will look on some docs and try to implement the support for this.

**Comment by michasoellner** [comment]
That would be awesome! :-)

**Comment by kovapatrik** [comment]
Btw according to Midea's naming convention, your device is a `fan`. Is that right? So can it only just circulate the air?

**Comment by kovapatrik** [comment]
Oh I've missed the exact name of your device in the title of the issue. It's indeed a fan.

**Comment by kovapatrik** [comment]
I've started to implement it now. Can you send me some screenshots of the app about the features the fan has? Or can you tell me what features would you need?

**Comment by michasoellner** [comment]
Hello. That sounds fantastic. I would love to turn it on/off and set the fan speed. I could send you screenshots or even a screen Capture of the app with all settings. 

Thanks in advance.

**Comment by kovapatrik** [comment]
Thank you! That's sounds simple enough. I just see there are these modes available: "Normal", "Natural", "Sleep", "Comfort", "Silent", "Baby", "Induction", "Circulation", "Strong", "Soft", "Customize", "Warm", "Smart". But maybe these are only available in some models.

**Comment by kovapatrik** [comment]
I've released beta version v1.0.7-beta.1 which should have support for Fan. I've skipped some functionalities (like oscillation, or auto fan mode), as I don't know how it's handled by the unit. Could you please install the beta, enable debug mode in your Homebridge instance, connect your unit to it and then control the device from the official Midea app and send the Homebridge logs? The values which are being set should be logged. Also, please note what you set in the Midea app when doing this.

**Comment by kovapatrik** [comment]
Also if you need help with any of the steps I mentioned, let me know.

**Comment by kovapatrik** [comment]
Did you have a chance to try it out?

**Comment by michasoellner** [comment]
> Did you have a chance to try it out?

My Fan isnt connection with the Wifi anymore. I`ve tried to reset the device multiple times, but it wont work. The Midea Support wants me to send the fan back in, but i bought it last year and i dont have the original packaging anymore. 

I will try to dissamble the Device, maybe i can hard reset it from the inside. 

I will let you know, when i got it working again. 

Thanks for all your work.

**Comment by kovapatrik** [comment]
Did you manage to make it work? Btw I think the units should have a way to hard reset them without disassembling them.

**Comment by kovapatrik** [comment]
Theoretically, the support for your unit is released with `v1.1.0`, but I won't close this issue until someone verifies it.

**Comment by kovapatrik** [comment]
Have you managed to try this out?

**Comment by kovapatrik** [comment]
Closing this until further discussions.
