### ISSUE TITLE
Error: No plugin was found for the platform "midea" in your config.json. Please make sure the corresponding plugin is installed correctly.

### ISSUE THREAD

**Issue by gklka** [kovapatrik/homebridge-midea-platform#79]
**Describe The Bug:**

I used v0.1.2 version which worked fine, but after today I updated to 1.0.3, I got the following message in console:

No plugin was found for the platform "midea" in your config.json. Please make sure the corresponding plugin is installed correctly.

**To Reproduce:**

1. update the plugin from the Homebridge web UI
2. on Plugins page, select Plugin config and add the air conditioner again (it finds the AC unit, adds the config)
3. restart Homebridge

**Expected behavior:**

I think the plugin registers for different name than "midea", and the Homekit server does not find it by this name

**Logs:**

```
[4/10/2024, 12:47:15 PM] No plugin was found for the platform "midea" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

**Plugin Config**

```json
        {
            "devices": [
                {
                    "type": "Air Conditioner",
                    "name": "Kondika",
                    "id": 146235046509617,
                    "advanced_options": {
                        "token": "[...]83ce0cfee8adee2491eba99c2265bf36479e10cd3dd4f4c72c2aa101b8baad23a658a12216ec9adc68c7947bab6793dda08",
                        "key": "[...]c351a5a208fd20773d22c34326ba8ceb3f76d8bdc2"
                    },
                    "AC_options": {
                        "heatingCapable": true,
                        "outDoorTemp": true,
                        "ecoSwitch": true
                    }
                }
            ],
            "platform": "midea"
        }
```

**Environment:**

- **Plugin Version**: 1.0.3, but tried it all the way back to 0.3, and it is the same
- **Homebridge Version**: 1.7.0
- **Node.js Version**: v20.12.1
- **NPM Version**: v10.5.0
- **Operating System**: Linux hitchcock 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kovapatrik** [comment]
It's weird you have the platform field in your config set to "midea", because in case of my plugin it never was that. It should be "midea-platform".

**Comment by kovapatrik** [comment]
Or maybe it was at the beginning, I just noticed you wrote v0.1.2. At the first glance I read that as v1.0.2 for some reason.

**Comment by kovapatrik** [comment]
Did it solve your issue?

**Comment by kovapatrik** [comment]
Closed until further help is needed.
