### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by bgeri85** [kovapatrik/homebridge-midea-platform#8]
- in ios homekit the on/off button/switch does nothing, changing cool-off-dry-heat works and moving the switch but vice versa is not - in homebridge its do the same as the default tile so its maybe unnecessary
- If the ac has two swing modes only one oscillationg come up in HK (marked that i have both vertical and horizontal) in HB found nothing
- Display off is not showing in HK - but i think its a homekit limitation (in homebridge it works)
- FanOnly mode is set but can’t see an option on the accessories neither in HB or HK
- IDK that activating eco mod is possible somehow through api

**Comment by kovapatrik** [comment]
1. I don't really understand the problem you have described. Is the display on/off switch doesn't work for you?
2. Yeah, thats the limitations of Apple Home app. I can only add one "Oscillate" switch.
3. Display on/off is there in the Home app, but it's nested in the AC device. Is this the switch you were talking about in point 1?
4. That's on me, I didn't implemented it yet.
5. I can add a button which activates eco mode if you want.

**Comment by kovapatrik** [comment]
I've published an updated which added the option for creating a switch for eco mode. Can you check if it works?

**Comment by bgeri85** [comment]
The switch is there but it is not activating ECO mode. I’ve tested it on two Mission 2 devices

**Comment by gimprota76** [comment]
The switch is there and it is activating ECO mode. I’ve tested it on two SK-105

**Comment by gimprota76** [comment]
Hi can you enable fan speed? Thank you for your work !!!

**Comment by kovapatrik** [comment]
Fan speed is available, but it can be hidden. The air conditioner accessory contains more device other than the air conditioner itself (for example the outdoor temperature sensor, the switch for the display, etc...). You can see these accessories when you click on the AC accessory which is a group. There will be an "Accessories" menu when you scroll down after you click on the device. There you can find all the devices associated to the AC. If you click on the air conditioner there and scroll down, there will be the fan speed. 

I will create a seperate fan service in the future I think to ease the setting of it.

**Comment by kovapatrik** [comment]
> The switch is there but it is not activating ECO mode. I’ve tested it on two Mission 2 devices

Someone had the same issue. It turned out if the AC must be in "Cool" mode for the ECO switch to work.

**Comment by BrutallDLX** [comment]
The exterior temperature is bugged when the AC is off. It shows -270°C. When turn on the AC it updates after a while or much faster if I open the SmartHome app.

**Comment by kovapatrik** [comment]
> The exterior temperature is bugged when the AC is off. It shows -270°C. When turn on the AC it updates after a while or much faster if I open the SmartHome app.

This is the limitation of the AC. It sends this value when it's not been used for a while.

**Comment by BrutallDLX** [comment]
The new 0.4.12 version doesn't update the exterior temperature.

**Comment by kovapatrik** [comment]
> The new 0.4.12 version doesn't update the exterior temperature.

I think that's almost impossible as the air conditioner part of the code didn't changed a bit. If you are sure this is happening, please open a new issue with more information provided.

**Comment by BrutallDLX** [comment]
> > The new 0.4.12 version doesn't update the exterior temperature.
> 
> I think that's almost impossible as the air conditioner part of the code didn't changed a bit. If you are sure this is happening, please open a new issue with more information provided.

I've tried many ways and the only fix I found is to quickly turn off and then on the ac in homebridge. Other way the temperature stays at -270°. In other words, if the ac stays too long off, as you have said previously, the exterior temperature isn't working, but now, when you turned on the ac this sensor doesn't update till you turn off and on. The 0.4.11 version didn't have this issue, I don't know what is producing this.

**Comment by kovapatrik** [comment]
I will close this issue now, as I've created seperated issues for the fan only mode (#58) and for the outdoor temperature (#57). 

In the future please create a new issue for feature requests or bug reports rather than commenting on a totally seperate issue.
