### ISSUE TITLE
Air Conditioner Temperature Control Not Working

### ISSUE THREAD

**Issue by jlokos** [kovapatrik/homebridge-midea-platform#85]
**Describe The Bug:**

Air Conditioner Temperature Control Not Working via Home App. 

Wrong temperatures being displayed in Home App. It is possible to occasionally tap correct spot but as you can see in screenshots the base temperatures are off. Furthermore cannot set temperature via Siri if you state 'Set AC to 70' the logs just show the 
```
[11/06/2024, 00:21:42] [midea-platform] [Air Conditioner] Set device attribute POWER to: true
```
 - not setting a specific temperature like 
 ```
[11/06/2024, 00:21:00] [midea-platform] [Air Conditioner] Set target temperature to: 30 
```

**Plugin Config:**

```json
{
    "devices": [
        {
            "type": "Air Conditioner",
            "name": "Air Conditioner",
            "id": ,
            "advanced_options": {
                "token": "",
                "key": ""
            },
            "AC_options": {
                "swingMode": "Vertical",
                "heatingCapable": false,
                "outDoorTemp": true,
                "ecoSwitch": true,
                "dryModeSwitch": true,
                "fanOnlyModeSwitch": true
            }
        }
    ],
    "platform": "midea-platform"
}
```

**Screenshots:**

![IMG_797B1A1391DB-1](https://github.com/kovapatrik/homebridge-midea-platform/assets/71952027/58af20a9-ead3-4656-9e2d-3224f4450ba1)
![IMG_797B1A1391DB-2](https://github.com/kovapatrik/homebridge-midea-platform/assets/71952027/a8a35031-f6d4-4bfc-931a-05276badb4d6)
![IMG_797B1A1391DB-3](https://github.com/kovapatrik/homebridge-midea-platform/assets/71952027/358a1a18-c257-4c6d-a357-d0bf4c02974e)
![IMG_797B1A1391DB-4](https://github.com/kovapatrik/homebridge-midea-platform/assets/71952027/9880b8b7-fdba-4389-8356-83c3f6e5dba8)

**Environment:**

- **Plugin Version**: v1.0.6-beta.7 (also tried non beta)
- **Homebridge Version**: 1.8.2
- **Node.js Version**: 20.11.1
- **Operating System**: Raspbian

**Comment by kovapatrik** [comment]
I'm not sure I understand the screenshots. Is the temperature just jumps around? Could you please explain this a bit?

**Comment by jlokos** [comment]
@kovapatrik It seems like the base (min and max) temperatures are off. Since i'm seeing numbers like 186. It should be set in Fahrenheit with a minimum of 60f and max of 86f. I cannot set temperature via Siri as well so if I say 'Set AC to 70' the Home Bridge logs just show the the device getting a call to turn on not to set temperature. Let me know if you need anything additional.

**Comment by kovapatrik** [comment]
could you please turn on debug mode in your Homebridge instance and send me the logs when you change the temperature?

**Comment by den1k** [comment]
this happens for me as well when the temperature in apple home is fahrenheit. Celcius works fine

**Comment by den1k** [comment]
this fixes it for me: 
![CleanShot 2024-07-02 at 14 32 50@2x](https://github.com/kovapatrik/homebridge-midea-platform/assets/4651810/fe900921-5e5b-4aab-aba9-89d4942fbc55)

**Comment by kovapatrik** [comment]
I might need to convert Celsius to Fahrenheit when the Fahrenheit setting is toggled. I will let you know when I publish a new beta version which includes the conversion.

**Comment by den1k** [comment]
thank you!

**Comment by kovapatrik** [comment]
I've done some research and it turned out that HomeKit uses Celsius everywhere, so Fahrenheit is just a visual thing in the Home app. I also switched my iPhone's temperature unit to Fahrenheit and it worked without any issues. I've used the latest published beta though, could you please try this with that version?

**Comment by jlokos** [comment]
My issues seem to be resolved with the latest updates! Thank you very much! One note - I do not see the Dry Mode switch even though I enabled that option to be created with the accessory. All else works perfect

**Comment by kovapatrik** [comment]
Hm, weird. Could you please try removing it from the cache of Homebridge? Maybe it will solve it.

**Comment by kovapatrik** [comment]
Any news on this one?
