### ISSUE TITLE
Midea MF200W100WB-14A Waschmaschine

### ISSUE THREAD

**Issue by Primello** [kovapatrik/homebridge-midea-platform#87]
Hi, 

i bought an Midea Washingmashine and it working in the "Smarthome" App From Midea.

Will there be support for this Washingmashine?

Bye

Jacek Jashari

**Comment by kovapatrik** [comment]
hello! could you please install the plugin and do a discovery? it contains informations for me which is needed to answer this question

**Comment by kovapatrik** [comment]
do you need help doing this step? I can't proceed with this until I get the information needed

**Comment by mgoeppl** [comment]
Hi, this is a dump of the discovery of my MF200 washer dryer:
Name | Type | Model | Id | Ver. | Token / Key | Local Ip | Add / Update
-- | -- | -- | -- | -- | -- | -- | --
midea_db_0155 | Unknown | 38123703 | 153931628080922 | 3 | tokentokentoken (dm if needed) | 10.0.4.214 | Not supported

**Comment by kovapatrik** [comment]
I've published `v1.1.2-beta.2`, which should include the front loading washers' support. Could you please try it out?

**Comment by mgoeppl** [comment]
It works perfectly- however, during the washing, it does not show the remaining time, but always "0:00".
![IMG_2249](https://github.com/user-attachments/assets/e0494b91-6d1a-4b59-acf4-ba92eec9c08e)

**Comment by mgoeppl** [comment]
Oh: and the plugin generates the following error every 10 seconds if the washing machine is off (it is then disconnected from the network):
```
[8/8/2024, 10:49:08 PM] [homebridge-midea-platform] Socket error:
Error: connect EHOSTUNREACH 10.0.4.214:6444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
[8/8/2024, 10:49:08 PM] [homebridge-midea-platform] Socket closed with error
```

Thank you so much for your great work on this plugin!

**Comment by kovapatrik** [comment]
Could you please try it again using the latest beta version?

**Comment by mgoeppl** [comment]
It mostly works - however, it counts the time down as seconds, not minutes. 
When 13 minutes are remaining, home counts down from 13 seconds.

**Comment by kovapatrik** [comment]
I've released `v1.2.0-beta.2`, which should contain a fix for this. Could you please check it and write feedback?

**Comment by mgoeppl** [comment]
Works perfectly! Thank you so much!

**Comment by kovapatrik** [comment]
Is there any other feature you would want?

**Comment by mgoeppl** [comment]
No, not really.
If you could get the dishwasher controls in #104 working, this might be a welcome feature for the washers, as well - but it's probably easier now to leave the washers as is for now and extend the functionality later on.

**Comment by kovapatrik** [comment]
Cool! Let me know if you need something. I just wrote a comment on the other issue. If you have any functionality in your mind, you can do the same process with your model. Just send me that file here or in email, and reopen this issue with the feature you need.
