### ISSUE TITLE
Separate the humidity sensor from dehumidifier so I can use it as its own sensor when creating automations. Similar to how the temp sensor is

### ISSUE THREAD

**Issue by nbraunstein** [kovapatrik/homebridge-midea-platform#88]
**Is your feature request related to a problem? Please describe:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by nbraunstein** [comment]
![image](https://github.com/kovapatrik/homebridge-midea-platform/assets/25289238/b71447b1-b5fa-4e79-9f73-95df78dd426f)

I'd like to have a separate sensor for humidity so I can use my dehumidifier's sensor to create automations. Like this temp sensor that is built into my dehumidifier.

**Comment by dkerr64** [comment]
This is interesting... HomeKit dehumidifier has current humidity as a characteristic, but the Apple Home app cannot use that as a sensor from which to create an automation... it can only use the on/off state of the dehumidifier.

I think it would be easy to add a separate service for humidity sensor.  I would not separate it, but rather I would leave the current humidity characteristic as it is, but then create a humidity sensor in addition based on a config setting, just like the temperature sensor is created.

**Comment by kovapatrik** [comment]
I've had issues like this before with other services (like an air purifier filter usage level couldn't be used in automation and such...), so it looks like this is common with accessories in the Home app.

**Comment by kovapatrik** [comment]
I've published `v1.1.0-beta.2` which contains the ability to toggle the `humiditySensor` config in the plugin configurations which should create the separated humidity sensor. Could you please try it out?

**Comment by mrbritten** [comment]
Not my request, but I can say it seems to be working great, I can use humidity level to trigger automations now.

**Comment by kovapatrik** [comment]
Thanks for the feedback!

**Comment by nbraunstein** [comment]
Thank you!!  Works perfectly

**Comment by kovapatrik** [comment]
Great to hear it! I will close this issue as soon as I release `v1.1.0`.
