### ISSUE TITLE
Need to add maintainers to package.json

### ISSUE THREAD

**Issue by dkerr64** [kovapatrik/homebridge-midea-platform#90]
See this [issue at Homebridge UI](https://github.com/homebridge/homebridge-config-ui-x/issues/2070)... a regression in NPM requires that we add maintainers field to package.json, at least for now until NPM fix their bug.  And you need to make sure that your Homebridge config UI-X is at version v4.56.3 or later (just published yesterday).

**Comment by kovapatrik** [comment]
Is this still an issue? I've seen your issues in the config UI repo, but as I see at my side, my UI is updated to `v4.56.4` without any issues.

**Comment by dkerr64** [comment]
Not sure if it is fixed in NPM yet, but the Homebridge UI folks did add it to their package in [v4.56.4](https://github.com/homebridge/homebridge-config-ui-x/commit/07720e8aca95780724d5b722ceb162ca5c9a4bf2) to ensure that anyone with an older version will see the option to upgrade to that.

But I don't know if other packages are still affected... I do see an indication to upgrade to this plugin's v1.1.0, but I think the UI may go down a different path if the current installed version is a beta (which mine was).

**Comment by kovapatrik** [comment]
I think it was fixed by NPM or somehow this package wasn't effected by this. What do you think? Can I close this?
