### ISSUE TITLE
New device discovered, you must add it to the config.json settings.

### ISSUE THREAD

**Issue by andretimar** [kovapatrik/homebridge-midea-platform#96]
**Describe The Bug:**

After a fresh install of the latest Homebridge and installing the latest version of the plugin I can successfully discover my device using my credentials from Midea. After I click Add (token visible) and I restart my Homebridge as instructed I get the message: 

`New device discovered, you must add it to the config.json settings.`

It seems like my config.json is empty, I found no sample code how to add it manually and retrieve my tokens as during adding it they are truncated.

The accessory doesn't become visible in Apple Home.

**Logs:**

```
[23/07/2024, 22:55:25] [midea-platform] Discovered device: {"ip":"192.168.0.25","port":6444,"id":152832116299415,"model":"00000Q19","sn":"000000P0000000Q19CC12D1233140000","name":"net_ac_3314","type":172,"version":3}
[23/07/2024, 22:55:25] [midea-platform] [net_ac_3314 | 192.168.0.25}] New device discovered, you must add it to the config.json settings.

```

**Plugin Config:**

```json
{
    "platform": "midea-platform"
}
```

**Screenshots:**

![Screenshot 2024-07-23 at 23 06 59](https://github.com/user-attachments/assets/f35527f5-496f-4215-b066-eb153bc97b3a)
![Screenshot 2024-07-23 at 23 05 27](https://github.com/user-attachments/assets/3e302775-7fce-41c1-ab59-403bd41d12fe)
![Screenshot 2024-07-23 at 23 04 49](https://github.com/user-attachments/assets/19687ca4-07be-4236-83fa-6767c754f518)

**Environment:**

- **Plugin Version**: v1.1.0
- **Homebridge Version**: v1.8.4
- **Node.js Version**: v20.12.2
- **NPM Version**: 
- **Operating System**:  Raspbian GNU/Linux Bookworm (12)
--

<br class="Apple-interchange-newline">

**Comment by kovapatrik** [comment]
After you add click on `Add`  you also need to save the form, with the save button at the bottom of it.

**Comment by andretimar** [comment]
Hey @kovapatrik thanks for the quick reply. I did that but here's a JAM recording for it - https://jam.dev/c/fb64a789-bbd4-483d-9219-397d5211e420

**Comment by kovapatrik** [comment]
It says its a private link.

**Comment by andretimar** [comment]
@kovapatrik sorry, should be public now.

**Comment by kovapatrik** [comment]
hm yeah, it should appear in the form as a new device and it's not doing that. let me check

**Comment by kovapatrik** [comment]
it's working at my end, maybe there are some extensions in your browser which blocks JavaScript code? or event the browser itself can do that

**Comment by andretimar** [comment]
Worked like a charm in incognito, thanks for the quick support, it's working perfectly now! 🇭🇺 🍺
